database:
  user: root
  password: root
  net: tcp
  addr: 127.0.0.1:3308
  dbname: project_management_demo_test
  allowNativePasswords: true
  params:
    parseTime: true
    charset: utf8mb4
    loc: Asia/Tokyo

server:
  address: 8081
