// Code generated by entc, DO NOT EDIT.

package teammate

import (
	"project-management-demo-backend/ent/schema/ulid"
	"time"
)

const (
	// Label holds the string label denoting the teammate type in the database.
	Label = "teammate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeWorkspaces holds the string denoting the workspaces edge name in mutations.
	EdgeWorkspaces = "workspaces"
	// EdgeProjects holds the string denoting the projects edge name in mutations.
	EdgeProjects = "projects"
	// EdgeProjectTeammates holds the string denoting the project_teammates edge name in mutations.
	EdgeProjectTeammates = "project_teammates"
	// EdgeWorkspaceTeammates holds the string denoting the workspace_teammates edge name in mutations.
	EdgeWorkspaceTeammates = "workspace_teammates"
	// EdgeFavoriteProjects holds the string denoting the favorite_projects edge name in mutations.
	EdgeFavoriteProjects = "favorite_projects"
	// EdgeFavoriteWorkspaces holds the string denoting the favorite_workspaces edge name in mutations.
	EdgeFavoriteWorkspaces = "favorite_workspaces"
	// EdgeTeammateTaskTabStatuses holds the string denoting the teammate_task_tab_statuses edge name in mutations.
	EdgeTeammateTaskTabStatuses = "teammate_task_tab_statuses"
	// EdgeTeammateTaskColumns holds the string denoting the teammate_task_columns edge name in mutations.
	EdgeTeammateTaskColumns = "teammate_task_columns"
	// EdgeTeammateTaskListStatuses holds the string denoting the teammate_task_list_statuses edge name in mutations.
	EdgeTeammateTaskListStatuses = "teammate_task_list_statuses"
	// EdgeTeammateTaskSections holds the string denoting the teammate_task_sections edge name in mutations.
	EdgeTeammateTaskSections = "teammate_task_sections"
	// Table holds the table name of the teammate in the database.
	Table = "teammates"
	// WorkspacesTable is the table that holds the workspaces relation/edge.
	WorkspacesTable = "workspaces"
	// WorkspacesInverseTable is the table name for the Workspace entity.
	// It exists in this package in order to avoid circular dependency with the "workspace" package.
	WorkspacesInverseTable = "workspaces"
	// WorkspacesColumn is the table column denoting the workspaces relation/edge.
	WorkspacesColumn = "created_by"
	// ProjectsTable is the table that holds the projects relation/edge.
	ProjectsTable = "projects"
	// ProjectsInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectsInverseTable = "projects"
	// ProjectsColumn is the table column denoting the projects relation/edge.
	ProjectsColumn = "created_by"
	// ProjectTeammatesTable is the table that holds the project_teammates relation/edge.
	ProjectTeammatesTable = "project_teammates"
	// ProjectTeammatesInverseTable is the table name for the ProjectTeammate entity.
	// It exists in this package in order to avoid circular dependency with the "projectteammate" package.
	ProjectTeammatesInverseTable = "project_teammates"
	// ProjectTeammatesColumn is the table column denoting the project_teammates relation/edge.
	ProjectTeammatesColumn = "teammate_id"
	// WorkspaceTeammatesTable is the table that holds the workspace_teammates relation/edge.
	WorkspaceTeammatesTable = "workspace_teammates"
	// WorkspaceTeammatesInverseTable is the table name for the WorkspaceTeammate entity.
	// It exists in this package in order to avoid circular dependency with the "workspaceteammate" package.
	WorkspaceTeammatesInverseTable = "workspace_teammates"
	// WorkspaceTeammatesColumn is the table column denoting the workspace_teammates relation/edge.
	WorkspaceTeammatesColumn = "teammate_id"
	// FavoriteProjectsTable is the table that holds the favorite_projects relation/edge.
	FavoriteProjectsTable = "favorite_projects"
	// FavoriteProjectsInverseTable is the table name for the FavoriteProject entity.
	// It exists in this package in order to avoid circular dependency with the "favoriteproject" package.
	FavoriteProjectsInverseTable = "favorite_projects"
	// FavoriteProjectsColumn is the table column denoting the favorite_projects relation/edge.
	FavoriteProjectsColumn = "teammate_id"
	// FavoriteWorkspacesTable is the table that holds the favorite_workspaces relation/edge.
	FavoriteWorkspacesTable = "favorite_workspaces"
	// FavoriteWorkspacesInverseTable is the table name for the FavoriteWorkspace entity.
	// It exists in this package in order to avoid circular dependency with the "favoriteworkspace" package.
	FavoriteWorkspacesInverseTable = "favorite_workspaces"
	// FavoriteWorkspacesColumn is the table column denoting the favorite_workspaces relation/edge.
	FavoriteWorkspacesColumn = "teammate_id"
	// TeammateTaskTabStatusesTable is the table that holds the teammate_task_tab_statuses relation/edge.
	TeammateTaskTabStatusesTable = "teammate_task_tab_status"
	// TeammateTaskTabStatusesInverseTable is the table name for the TeammateTaskTabStatus entity.
	// It exists in this package in order to avoid circular dependency with the "teammatetasktabstatus" package.
	TeammateTaskTabStatusesInverseTable = "teammate_task_tab_status"
	// TeammateTaskTabStatusesColumn is the table column denoting the teammate_task_tab_statuses relation/edge.
	TeammateTaskTabStatusesColumn = "teammate_id"
	// TeammateTaskColumnsTable is the table that holds the teammate_task_columns relation/edge.
	TeammateTaskColumnsTable = "teammate_task_columns"
	// TeammateTaskColumnsInverseTable is the table name for the TeammateTaskColumn entity.
	// It exists in this package in order to avoid circular dependency with the "teammatetaskcolumn" package.
	TeammateTaskColumnsInverseTable = "teammate_task_columns"
	// TeammateTaskColumnsColumn is the table column denoting the teammate_task_columns relation/edge.
	TeammateTaskColumnsColumn = "teammate_id"
	// TeammateTaskListStatusesTable is the table that holds the teammate_task_list_statuses relation/edge.
	TeammateTaskListStatusesTable = "teammate_task_list_status"
	// TeammateTaskListStatusesInverseTable is the table name for the TeammateTaskListStatus entity.
	// It exists in this package in order to avoid circular dependency with the "teammatetaskliststatus" package.
	TeammateTaskListStatusesInverseTable = "teammate_task_list_status"
	// TeammateTaskListStatusesColumn is the table column denoting the teammate_task_list_statuses relation/edge.
	TeammateTaskListStatusesColumn = "teammate_id"
	// TeammateTaskSectionsTable is the table that holds the teammate_task_sections relation/edge.
	TeammateTaskSectionsTable = "teammate_task_sections"
	// TeammateTaskSectionsInverseTable is the table name for the TeammateTaskSection entity.
	// It exists in this package in order to avoid circular dependency with the "teammatetasksection" package.
	TeammateTaskSectionsInverseTable = "teammate_task_sections"
	// TeammateTaskSectionsColumn is the table column denoting the teammate_task_sections relation/edge.
	TeammateTaskSectionsColumn = "teammate_id"
)

// Columns holds all SQL columns for teammate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldImage,
	FieldEmail,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ImageValidator is a validator for the "image" field. It is called by the builders before save.
	ImageValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)
