// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (c *ColorQuery) CollectFields(ctx context.Context, satisfies ...string) *ColorQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		c = c.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return c
}

func (c *ColorQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *ColorQuery {
	return c
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (i *IconQuery) CollectFields(ctx context.Context, satisfies ...string) *IconQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		i = i.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return i
}

func (i *IconQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *IconQuery {
	return i
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (t *TeammateQuery) CollectFields(ctx context.Context, satisfies ...string) *TeammateQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		t = t.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return t
}

func (t *TeammateQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TeammateQuery {
	return t
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (tt *TestTodoQuery) CollectFields(ctx context.Context, satisfies ...string) *TestTodoQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		tt = tt.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return tt
}

func (tt *TestTodoQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TestTodoQuery {
	return tt
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (tu *TestUserQuery) CollectFields(ctx context.Context, satisfies ...string) *TestUserQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		tu = tu.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return tu
}

func (tu *TestUserQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TestUserQuery {
	return tu
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (w *WorkspaceQuery) CollectFields(ctx context.Context, satisfies ...string) *WorkspaceQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		w = w.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return w
}

func (w *WorkspaceQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *WorkspaceQuery {
	return w
}
