// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/tasklistcompletedstatus"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskListCompletedStatusCreate is the builder for creating a TaskListCompletedStatus entity.
type TaskListCompletedStatusCreate struct {
	config
	mutation *TaskListCompletedStatusMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tlcsc *TaskListCompletedStatusCreate) SetName(s string) *TaskListCompletedStatusCreate {
	tlcsc.mutation.SetName(s)
	return tlcsc
}

// SetStatusCode sets the "status_code" field.
func (tlcsc *TaskListCompletedStatusCreate) SetStatusCode(tc tasklistcompletedstatus.StatusCode) *TaskListCompletedStatusCreate {
	tlcsc.mutation.SetStatusCode(tc)
	return tlcsc
}

// SetCreatedAt sets the "created_at" field.
func (tlcsc *TaskListCompletedStatusCreate) SetCreatedAt(t time.Time) *TaskListCompletedStatusCreate {
	tlcsc.mutation.SetCreatedAt(t)
	return tlcsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tlcsc *TaskListCompletedStatusCreate) SetNillableCreatedAt(t *time.Time) *TaskListCompletedStatusCreate {
	if t != nil {
		tlcsc.SetCreatedAt(*t)
	}
	return tlcsc
}

// SetUpdatedAt sets the "updated_at" field.
func (tlcsc *TaskListCompletedStatusCreate) SetUpdatedAt(t time.Time) *TaskListCompletedStatusCreate {
	tlcsc.mutation.SetUpdatedAt(t)
	return tlcsc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tlcsc *TaskListCompletedStatusCreate) SetNillableUpdatedAt(t *time.Time) *TaskListCompletedStatusCreate {
	if t != nil {
		tlcsc.SetUpdatedAt(*t)
	}
	return tlcsc
}

// SetID sets the "id" field.
func (tlcsc *TaskListCompletedStatusCreate) SetID(u ulid.ID) *TaskListCompletedStatusCreate {
	tlcsc.mutation.SetID(u)
	return tlcsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tlcsc *TaskListCompletedStatusCreate) SetNillableID(u *ulid.ID) *TaskListCompletedStatusCreate {
	if u != nil {
		tlcsc.SetID(*u)
	}
	return tlcsc
}

// Mutation returns the TaskListCompletedStatusMutation object of the builder.
func (tlcsc *TaskListCompletedStatusCreate) Mutation() *TaskListCompletedStatusMutation {
	return tlcsc.mutation
}

// Save creates the TaskListCompletedStatus in the database.
func (tlcsc *TaskListCompletedStatusCreate) Save(ctx context.Context) (*TaskListCompletedStatus, error) {
	var (
		err  error
		node *TaskListCompletedStatus
	)
	tlcsc.defaults()
	if len(tlcsc.hooks) == 0 {
		if err = tlcsc.check(); err != nil {
			return nil, err
		}
		node, err = tlcsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskListCompletedStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tlcsc.check(); err != nil {
				return nil, err
			}
			tlcsc.mutation = mutation
			if node, err = tlcsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tlcsc.hooks) - 1; i >= 0; i-- {
			if tlcsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tlcsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tlcsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tlcsc *TaskListCompletedStatusCreate) SaveX(ctx context.Context) *TaskListCompletedStatus {
	v, err := tlcsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlcsc *TaskListCompletedStatusCreate) Exec(ctx context.Context) error {
	_, err := tlcsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlcsc *TaskListCompletedStatusCreate) ExecX(ctx context.Context) {
	if err := tlcsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tlcsc *TaskListCompletedStatusCreate) defaults() {
	if _, ok := tlcsc.mutation.CreatedAt(); !ok {
		v := tasklistcompletedstatus.DefaultCreatedAt()
		tlcsc.mutation.SetCreatedAt(v)
	}
	if _, ok := tlcsc.mutation.UpdatedAt(); !ok {
		v := tasklistcompletedstatus.DefaultUpdatedAt()
		tlcsc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tlcsc.mutation.ID(); !ok {
		v := tasklistcompletedstatus.DefaultID()
		tlcsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tlcsc *TaskListCompletedStatusCreate) check() error {
	if _, ok := tlcsc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if v, ok := tlcsc.mutation.Name(); ok {
		if err := tasklistcompletedstatus.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "name": %w`, err)}
		}
	}
	if _, ok := tlcsc.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "status_code"`)}
	}
	if v, ok := tlcsc.mutation.StatusCode(); ok {
		if err := tasklistcompletedstatus.StatusCodeValidator(v); err != nil {
			return &ValidationError{Name: "status_code", err: fmt.Errorf(`ent: validator failed for field "status_code": %w`, err)}
		}
	}
	if _, ok := tlcsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := tlcsc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	return nil
}

func (tlcsc *TaskListCompletedStatusCreate) sqlSave(ctx context.Context) (*TaskListCompletedStatus, error) {
	_node, _spec := tlcsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tlcsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(ulid.ID)
	}
	return _node, nil
}

func (tlcsc *TaskListCompletedStatusCreate) createSpec() (*TaskListCompletedStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskListCompletedStatus{config: tlcsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tasklistcompletedstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: tasklistcompletedstatus.FieldID,
			},
		}
	)
	if id, ok := tlcsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tlcsc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tasklistcompletedstatus.FieldName,
		})
		_node.Name = value
	}
	if value, ok := tlcsc.mutation.StatusCode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: tasklistcompletedstatus.FieldStatusCode,
		})
		_node.StatusCode = value
	}
	if value, ok := tlcsc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tasklistcompletedstatus.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tlcsc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tasklistcompletedstatus.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TaskListCompletedStatusCreateBulk is the builder for creating many TaskListCompletedStatus entities in bulk.
type TaskListCompletedStatusCreateBulk struct {
	config
	builders []*TaskListCompletedStatusCreate
}

// Save creates the TaskListCompletedStatus entities in the database.
func (tlcscb *TaskListCompletedStatusCreateBulk) Save(ctx context.Context) ([]*TaskListCompletedStatus, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tlcscb.builders))
	nodes := make([]*TaskListCompletedStatus, len(tlcscb.builders))
	mutators := make([]Mutator, len(tlcscb.builders))
	for i := range tlcscb.builders {
		func(i int, root context.Context) {
			builder := tlcscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskListCompletedStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tlcscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tlcscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tlcscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tlcscb *TaskListCompletedStatusCreateBulk) SaveX(ctx context.Context) []*TaskListCompletedStatus {
	v, err := tlcscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tlcscb *TaskListCompletedStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := tlcscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tlcscb *TaskListCompletedStatusCreateBulk) ExecX(ctx context.Context) {
	if err := tlcscb.Exec(ctx); err != nil {
		panic(err)
	}
}
