// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/teammatetabstatus"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeammateTabStatusDelete is the builder for deleting a TeammateTabStatus entity.
type TeammateTabStatusDelete struct {
	config
	hooks    []Hook
	mutation *TeammateTabStatusMutation
}

// Where appends a list predicates to the TeammateTabStatusDelete builder.
func (ttsd *TeammateTabStatusDelete) Where(ps ...predicate.TeammateTabStatus) *TeammateTabStatusDelete {
	ttsd.mutation.Where(ps...)
	return ttsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ttsd *TeammateTabStatusDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ttsd.hooks) == 0 {
		affected, err = ttsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TeammateTabStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ttsd.mutation = mutation
			affected, err = ttsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ttsd.hooks) - 1; i >= 0; i-- {
			if ttsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttsd *TeammateTabStatusDelete) ExecX(ctx context.Context) int {
	n, err := ttsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ttsd *TeammateTabStatusDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: teammatetabstatus.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: teammatetabstatus.FieldID,
			},
		},
	}
	if ps := ttsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ttsd.driver, _spec)
}

// TeammateTabStatusDeleteOne is the builder for deleting a single TeammateTabStatus entity.
type TeammateTabStatusDeleteOne struct {
	ttsd *TeammateTabStatusDelete
}

// Exec executes the deletion query.
func (ttsdo *TeammateTabStatusDeleteOne) Exec(ctx context.Context) error {
	n, err := ttsdo.ttsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teammatetabstatus.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ttsdo *TeammateTabStatusDeleteOne) ExecX(ctx context.Context) {
	ttsdo.ttsd.ExecX(ctx)
}
