// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Teammate is the predicate function for teammate builders.
type Teammate func(*sql.Selector)

// TestTodo is the predicate function for testtodo builders.
type TestTodo func(*sql.Selector)

// TestUser is the predicate function for testuser builders.
type TestUser func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)
